modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="expantion_minecraft"
version="1.0.0"
displayName="Expantion Minecraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="famille, MCreator"

[[dependencies.expantion_minecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



